### ISSUE TITLE
Pass options to VimFiler

### ISSUE THREAD

**Issue by felixSchl** [romgrk/vimfiler-prompt#1]
Is it possible to pass options down to the `VimFiler` command? I am looking in particular for `-fnamewidth`

**Comment by romgrk** [comment]
I'm afraid I don't understand. At which moment would you like to pass an option?
I'v updated the script to expose the prototype under `g:vimfiler_prompt_prototype`, if you want to patch locally, go ahead, otherwise I'm all ears.
